//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 09/10/2016 12:06:47
namespace CrossingFingers_Wave
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Fonts
            {
                
                /// <summary> Path to Content/Assets/Fonts/HelveticaRounded_16.ttf </summary>
                public const string HelveticaRounded_16_ttf = "Content/Assets/Fonts/HelveticaRounded_16.ttf";
                
                /// <summary> Path to Content/Assets/Fonts/Kabel Dm BT_18.TTF </summary>
                public const string Kabel_Dm_BT_18_TTF = "Content/Assets/Fonts/Kabel Dm BT_18.TTF";
                
                /// <summary> Path to Content/Assets/Fonts/Kabel Dm BT_24.TTF </summary>
                public const string Kabel_Dm_BT_24_TTF = "Content/Assets/Fonts/Kabel Dm BT_24.TTF";
                
                /// <summary> Path to Content/Assets/Fonts/Kabel Dm BT_32.TTF </summary>
                public const string Kabel_Dm_BT_32_TTF = "Content/Assets/Fonts/Kabel Dm BT_32.TTF";
                
                /// <summary> Path to Content/Assets/Fonts/Kabel Dm BT_36.TTF </summary>
                public const string Kabel_Dm_BT_36_TTF = "Content/Assets/Fonts/Kabel Dm BT_36.TTF";
                
                /// <summary> Path to Content/Assets/Fonts/Kabel Ult BT_18.TTF </summary>
                public const string Kabel_Ult_BT_18_TTF = "Content/Assets/Fonts/Kabel Ult BT_18.TTF";
                
                /// <summary> Path to Content/Assets/Fonts/Kabel Ult BT_24.TTF </summary>
                public const string Kabel_Ult_BT_24_TTF = "Content/Assets/Fonts/Kabel Ult BT_24.TTF";
            }
            
            public sealed class Music
            {
                
                /// <summary> Path to Content/Assets/Music/BackgroundMusic.mp3 </summary>
                public const string BackgroundMusic_mp3 = "Content/Assets/Music/BackgroundMusic.mp3";
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/Button.wav </summary>
                public const string Button_wav = "Content/Assets/Sounds/Button.wav";
                
                /// <summary> Path to Content/Assets/Sounds/Clap.wav </summary>
                public const string Clap_wav = "Content/Assets/Sounds/Clap.wav";
                
                /// <summary> Path to Content/Assets/Sounds/Lose.wav </summary>
                public const string Lose_wav = "Content/Assets/Sounds/Lose.wav";
                
                /// <summary> Path to Content/Assets/Sounds/Pick.wav </summary>
                public const string Pick_wav = "Content/Assets/Sounds/Pick.wav";
                
                /// <summary> Path to Content/Assets/Sounds/Rotating.wav </summary>
                public const string Rotating_wav = "Content/Assets/Sounds/Rotating.wav";
                
                /// <summary> Path to Content/Assets/Sounds/Timer.wav </summary>
                public const string Timer_wav = "Content/Assets/Sounds/Timer.wav";
                
                /// <summary> Path to Content/Assets/Sounds/Win.wav </summary>
                public const string Win_wav = "Content/Assets/Sounds/Win.wav";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/Background.png </summary>
                public const string Background_png = "Content/Assets/Textures/Background.png";
                
                /// <summary> Path to Content/Assets/Textures/BackgroundPlayers.png </summary>
                public const string BackgroundPlayers_png = "Content/Assets/Textures/BackgroundPlayers.png";
                
                /// <summary> Path to Content/Assets/Textures/BackgroundRules.png </summary>
                public const string BackgroundRules_png = "Content/Assets/Textures/BackgroundRules.png";
                
                /// <summary> Path to Content/Assets/Textures/Circle.png </summary>
                public const string Circle_png = "Content/Assets/Textures/Circle.png";
                
                /// <summary> Path to Content/Assets/Textures/Logo.png </summary>
                public const string Logo_png = "Content/Assets/Textures/Logo.png";
                
                /// <summary> Path to Content/Assets/Textures/PageShadow.png </summary>
                public const string PageShadow_png = "Content/Assets/Textures/PageShadow.png";
                
                /// <summary> Path to Content/Assets/Textures/Pixel.png </summary>
                public const string Pixel_png = "Content/Assets/Textures/Pixel.png";
                
                /// <summary> Path to Content/Assets/Textures/PlayGameOverPopupLose.png </summary>
                public const string PlayGameOverPopupLose_png = "Content/Assets/Textures/PlayGameOverPopupLose.png";
                
                /// <summary> Path to Content/Assets/Textures/PlayGameOverPopupPlayer1Win.png </summary>
                public const string PlayGameOverPopupPlayer1Win_png = "Content/Assets/Textures/PlayGameOverPopupPlayer1Win.png";
                
                /// <summary> Path to Content/Assets/Textures/PlayGameOverPopupPlayer2Win.png </summary>
                public const string PlayGameOverPopupPlayer2Win_png = "Content/Assets/Textures/PlayGameOverPopupPlayer2Win.png";
                
                /// <summary> Path to Content/Assets/Textures/PlayGameOverPopupWin.png </summary>
                public const string PlayGameOverPopupWin_png = "Content/Assets/Textures/PlayGameOverPopupWin.png";
                
                public sealed class Buttons
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/Button1Player.png </summary>
                    public const string Button1Player_png = "Content/Assets/Textures/Buttons/Button1Player.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/Button1PlayerOver.png </summary>
                    public const string Button1PlayerOver_png = "Content/Assets/Textures/Buttons/Button1PlayerOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/Button2PlayersBasicPlay.png </summary>
                    public const string Button2PlayersBasicPlay_png = "Content/Assets/Textures/Buttons/Button2PlayersBasicPlay.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/Button2PlayersBasicPlayOver.png </summary>
                    public const string Button2PlayersBasicPlayOver_png = "Content/Assets/Textures/Buttons/Button2PlayersBasicPlayOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/Button2PlayersRoulette.png </summary>
                    public const string Button2PlayersRoulette_png = "Content/Assets/Textures/Buttons/Button2PlayersRoulette.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/Button2PlayersRouletteOver.png </summary>
                    public const string Button2PlayersRouletteOver_png = "Content/Assets/Textures/Buttons/Button2PlayersRouletteOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonBackCross.png </summary>
                    public const string ButtonBackCross_png = "Content/Assets/Textures/Buttons/ButtonBackCross.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonBackCrossOver.png </summary>
                    public const string ButtonBackCrossOver_png = "Content/Assets/Textures/Buttons/ButtonBackCrossOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonGoBack.png </summary>
                    public const string ButtonGoBack_png = "Content/Assets/Textures/Buttons/ButtonGoBack.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonGoBackOver.png </summary>
                    public const string ButtonGoBackOver_png = "Content/Assets/Textures/Buttons/ButtonGoBackOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonGoBasicPlay.png </summary>
                    public const string ButtonGoBasicPlay_png = "Content/Assets/Textures/Buttons/ButtonGoBasicPlay.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonGoBasicPlayOver.png </summary>
                    public const string ButtonGoBasicPlayOver_png = "Content/Assets/Textures/Buttons/ButtonGoBasicPlayOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonGoRoulette.png </summary>
                    public const string ButtonGoRoulette_png = "Content/Assets/Textures/Buttons/ButtonGoRoulette.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonGoRouletteOver.png </summary>
                    public const string ButtonGoRouletteOver_png = "Content/Assets/Textures/Buttons/ButtonGoRouletteOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonLeft.png </summary>
                    public const string ButtonLeft_png = "Content/Assets/Textures/Buttons/ButtonLeft.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonLeftDisabled.png </summary>
                    public const string ButtonLeftDisabled_png = "Content/Assets/Textures/Buttons/ButtonLeftDisabled.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonLeftOver.png </summary>
                    public const string ButtonLeftOver_png = "Content/Assets/Textures/Buttons/ButtonLeftOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonPlay.png </summary>
                    public const string ButtonPlay_png = "Content/Assets/Textures/Buttons/ButtonPlay.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonPlayAgain.png </summary>
                    public const string ButtonPlayAgain_png = "Content/Assets/Textures/Buttons/ButtonPlayAgain.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonPlayAgainOver.png </summary>
                    public const string ButtonPlayAgainOver_png = "Content/Assets/Textures/Buttons/ButtonPlayAgainOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonPlayOver.png </summary>
                    public const string ButtonPlayOver_png = "Content/Assets/Textures/Buttons/ButtonPlayOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonRight.png </summary>
                    public const string ButtonRight_png = "Content/Assets/Textures/Buttons/ButtonRight.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonRightDisabled.png </summary>
                    public const string ButtonRightDisabled_png = "Content/Assets/Textures/Buttons/ButtonRightDisabled.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonRightOver.png </summary>
                    public const string ButtonRightOver_png = "Content/Assets/Textures/Buttons/ButtonRightOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonRoulette.png </summary>
                    public const string ButtonRoulette_png = "Content/Assets/Textures/Buttons/ButtonRoulette.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonRouletteOver.png </summary>
                    public const string ButtonRouletteOver_png = "Content/Assets/Textures/Buttons/ButtonRouletteOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonRules.png </summary>
                    public const string ButtonRules_png = "Content/Assets/Textures/Buttons/ButtonRules.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ButtonRulesOver.png </summary>
                    public const string ButtonRulesOver_png = "Content/Assets/Textures/Buttons/ButtonRulesOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ToggleButtonAutomaticOff.png </summary>
                    public const string ToggleButtonAutomaticOff_png = "Content/Assets/Textures/Buttons/ToggleButtonAutomaticOff.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ToggleButtonAutomaticOn.png </summary>
                    public const string ToggleButtonAutomaticOn_png = "Content/Assets/Textures/Buttons/ToggleButtonAutomaticOn.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ToggleButtonAutomaticOver.png </summary>
                    public const string ToggleButtonAutomaticOver_png = "Content/Assets/Textures/Buttons/ToggleButtonAutomaticOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ToggleButtonMusicOff.png </summary>
                    public const string ToggleButtonMusicOff_png = "Content/Assets/Textures/Buttons/ToggleButtonMusicOff.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ToggleButtonMusicOn.png </summary>
                    public const string ToggleButtonMusicOn_png = "Content/Assets/Textures/Buttons/ToggleButtonMusicOn.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ToggleButtonMusicOver.png </summary>
                    public const string ToggleButtonMusicOver_png = "Content/Assets/Textures/Buttons/ToggleButtonMusicOver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ToggleButtonSoundsOff.png </summary>
                    public const string ToggleButtonSoundsOff_png = "Content/Assets/Textures/Buttons/ToggleButtonSoundsOff.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ToggleButtonSoundsOn.png </summary>
                    public const string ToggleButtonSoundsOn_png = "Content/Assets/Textures/Buttons/ToggleButtonSoundsOn.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Buttons/ToggleButtonSoundsOver.png </summary>
                    public const string ToggleButtonSoundsOver_png = "Content/Assets/Textures/Buttons/ToggleButtonSoundsOver.png";
                }
                
                public sealed class Roulette
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Roulette/Needle.png </summary>
                    public const string Needle_png = "Content/Assets/Textures/Roulette/Needle.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Roulette/Roulette.png </summary>
                    public const string Roulette_png = "Content/Assets/Textures/Roulette/Roulette.png";
                }
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MainMenuScene.wscene </summary>
            public const string MainMenuScene = "Content/Scenes/MainMenuScene.wscene";
            
            /// <summary> Path to Content/Scenes/PlayersPopupScene.wscene </summary>
            public const string PlayersPopupScene = "Content/Scenes/PlayersPopupScene.wscene";
            
            /// <summary> Path to Content/Scenes/PlayGameOverPopupScene.wscene </summary>
            public const string PlayGameOverPopupScene = "Content/Scenes/PlayGameOverPopupScene.wscene";
            
            /// <summary> Path to Content/Scenes/PlayRouletteScene.wscene </summary>
            public const string PlayRouletteScene = "Content/Scenes/PlayRouletteScene.wscene";
            
            /// <summary> Path to Content/Scenes/PlayScene.wscene </summary>
            public const string PlayScene = "Content/Scenes/PlayScene.wscene";
            
            /// <summary> Path to Content/Scenes/RulesScene.wscene </summary>
            public const string RulesScene = "Content/Scenes/RulesScene.wscene";
        }
    }
}
